GET http://localhost:3000/
Accept: application/json

###

GET http://localhost:3000/draft
Accept: application/json

###

PUT http://localhost:3000/draft
Accept: application/json

###

PUT http://localhost:3000/draft
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya"}

###
