POST http://localhost:3000/draft/save
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya"}

###

POST http://localhost:3000/draft/update
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya","version":1}

###

GET http://localhost:3000/draft/versions
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya"}

###

GET http://localhost:3000/draft/by-version
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya","version":1}

###

GET http://localhost:3000/draft/last
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya"}

###

DELETE http://localhost:3000/draft
Content-Type: application/x-www-form-urlencoded

parameters={"asGuid":"12345","user":"Vasya","version":1}

###
